# Dockerfile для разработки
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы зависимостей
COPY package*.json ./
COPY yarn.lock ./

# Устанавливаем зависимости
RUN yarn install

# Копируем остальные файлы
COPY . .

# Открываем порт
EXPOSE 3000

# Запускаем в режиме разработки
CMD ["yarn", "dev"] 